module.exports = {
  DEFAULT_TIMEOUT: 60000,
  USER_AGENT: "Heartbeat-Service/1.0",
  SUCCESS_EXIT_CODE: 0,
  FAILURE_EXIT_CODE: 1,
  COLD_START_THRESHOLD_MS: 10000,
  MAX_RETRIES: 2,
  RETRY_DELAY_MS: 2000,
};
